
List<StageDef> stageDefs = [
        new StageDef("2.6.3"),
        new StageDef("2.6.2"),
        new StageDef("2.0.0")]

def branches = [:]

for (module in stageDefs) {
    branches[module.jacksonVersion] = {
        node('!master') {
            withEnv(["PATH+MAVEN=${tool 'Maven 3'}/bin"]) {

                stage("Build ThymeLeaf with Jackson ${module.jacksonVersion}") {
                    try {
                        git 'https://github.com/thymeleaf/thymeleaf.git'
                        sh "mvn -B clean install -Djackson.version=${module.jacksonVersion}"
                    } catch (e) {
                        echo "BUILD FAILED: ${e.getMessage()}"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
    }
}

parallel branches

class StageDef implements Serializable {

    String jacksonVersion

    StageDef(final String jacksonVersion) {
        this.jacksonVersion = jacksonVersion
    }
}
