List<Module> modules = [
        new Module("3.0.6.RELEASE"),
        new Module("3.0.5.RELEASE"),
        new Module("2.1.5.RELEASE")]

def branches = [:]

for (module in modules) {
    branches[module.thymeLeafVersion] = {
        node('!master') {
            withEnv(["PATH+MAVEN=${tool 'Maven 3'}/bin"]) {

                stage("thymeleaf.version=${module.thymeLeafVersion}") {
                    try {
                        git 'https://github.com/spring-projects/spring-petclinic'
                        sh "mvn -B clean install -Dthymeleaf.version=${module.thymeLeafVersion}"
                    } catch (Throwable) {
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
    }
}
node {
    echo branches.toString()
}

parallel branches

class Module implements Serializable {

    String thymeLeafVersion

    Module(final String thymeLeafVersion) {
        this.thymeLeafVersion = thymeLeafVersion
    }
}
