withCredentials([usernamePassword(credentialsId: 'Deployserver', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {

    springBootPipeline {
        hostname = 'jenkinslab-deployserver'
        port = '9092'
        username = '$USERNAME'
        filename = 'service-2-0.0.1-SNAPSHOT.jar'
        servicename = 'service-2'
    }
}