node {
    try {
        stage('Checkout') {
            git url: 'https://github.com/comsysto/jenkins-lab-shared-pipeline.git', credentialsId: 'GITHUB_CRED'
        }

        dir('service-2') {

            stage('Build') {
                sh './gradlew clean build'
            }

            stage('Deploy') {
                sshagent(credentials: ['VAGRANT-SSH']) {
                    sh 'ssh -o StrictHostKeyChecking=no vagrant@192.168.33.10  mkdir -p service-2'
                    sh 'ssh -o StrictHostKeyChecking=no vagrant@192.168.33.10 ./service-2/shutdown.sh || true'
                    sh 'scp -o StrictHostKeyChecking=no build/libs/service-2-0.0.1-SNAPSHOT.jar startup.sh shutdown.sh vagrant@192.168.33.10:~/service-2/'
                    sh 'ssh -o StrictHostKeyChecking=no agrant@192.168.33.10 chmod -R 755 /service-2'
                    sh 'ssh -o StrictHostKeyChecking=no vagrant@192.168.33.10 ./service-2/startup.sh &'
                }
            }



        }
    } catch (exc) {
        echo "Caught: ${exc}"
        currentBuild.result = 'FAILURE'
    }
}