echo 'starting'
node {
    stage('Checkout') {
        git url: 'https://github.com/comsysto/jenkins-lab-shared-pipeline.git', credentialsId: 'GITHUB_CRED'
    }
    dir('service-2'){
        stage('Build') {
            sh './gradlew clean build'

        }
        stage('Deploy'){
            sshagent (credentials: ['VAGRANT-SSH']) {
                sh 'ssh vagrant@192.168.33.10 -o StrictHostKeyChecking=no'
            }
        }
        stage('Results') {
            junit '**/target/surefire-reports/TEST-*.xml'
            archive 'target/*.jar'
        }
    }
}