node {
	try {
		stage('Checkout') {
			echo 'Checkout'
			checkout scm
			sh 'git clean -dfx'
		}

		dir('service-1') {	
			stage('Build') {
				sh 'gradle build'
			}
			
			stage('Deploy') {
			
			}
			
			stage('Healthcheck') {
			
			}
		}
	}
	catch (exc) {
		echo 'Something failed, I should sound the klaxons!'
		throw exc
	}
}