node {
	try {
		stage('Checkout') {
			echo 'Checkout'
			git url: 'https://github.com/comsysto/jenkins-lab-shared-pipeline.git'
			sh 'git clean -dfx'
		}

		dir('service-1') {	
			stage('Build') {
				sh 'mvn clean install'
			}
			
			stage('Deploy') {
			
			}
			
			stage('Healthcheck') {
			
			}
		}
	}
	catch (exc) {
		echo 'Something failed, I should sound the klaxons!'
		throw
	}
}