node {
	try {
		stage('Checkout') {
			echo 'Checkout'
			checkout scm
			sh 'git clean -dfx'
		}

		dir('service-1') {	
			stage('Build') {
				env.PATH = "${tool 'gradle'}/bin:${env.PATH}"
				sh 'gradle build'
			}
			
			stage('Deploy') {
				sh 'scp build/libs/service-1-0.0.1-SNAPSHOT.jar matthias@192.168.99.101:~/jenkinslab/service-1-0.0.1-SNAPSHOT.jar'
				sh 'ssh matthias@192.168.99.101 kill $(ps aux | grep service-1-0.0.1-SNAPSHOT.jar | awk "{print $2}")'
				sh 'ssh matthias@192.168.99.101 nohup java -jar jenkinslab/service-1-0.0.1-SNAPSHOT.jar &'
			}
			
			stage('Healthcheck') {
			
			}
		}
	}
	catch (exc) {
		echo "Caught: ${exc}"
		currentBuild.result = 'FAILURE'
	}
}